-- MySQL Script generated by MySQL Workbench
-- Sat Sep 29 17:25:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `pasword` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `country` VARCHAR(45) NOT NULL DEFAULT 'Serbia',
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pet` (
  `idPet` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Has_Pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Has_Pets` (
  `User_idUser` INT NOT NULL,
  `Pet_idPet` INT NOT NULL,
  INDEX `fk_User_Has_Pets_User_idx` (`User_idUser` ASC),
  INDEX `fk_User_Has_Pets_Pet1_idx` (`Pet_idPet` ASC),
  CONSTRAINT `fk_User_Has_Pets_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Has_Pets_Pet1`
    FOREIGN KEY (`Pet_idPet`)
    REFERENCES `mydb`.`Pet` (`idPet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet_Shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pet_Shop` (
  `idPetShop` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `pasword` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `country` VARCHAR(45) NOT NULL DEFAULT 'Serbia',
  PRIMARY KEY (`idPetShop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Food` (
  `idFood` INT NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL,
  PRIMARY KEY (`idFood`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet_Shop_Has_Food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pet_Shop_Has_Food` (
  `Food_idFood` INT NOT NULL,
  `Pet_Shop_idPetShop` INT NOT NULL,
  `amount` DECIMAL(3) NOT NULL,
  INDEX `fk_Pet_Shop_Has_Food_Food1_idx` (`Food_idFood` ASC),
  INDEX `fk_Pet_Shop_Has_Food_Pet_Shop1_idx` (`Pet_Shop_idPetShop` ASC),
  CONSTRAINT `fk_Pet_Shop_Has_Food_Food1`
    FOREIGN KEY (`Food_idFood`)
    REFERENCES `mydb`.`Food` (`idFood`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pet_Shop_Has_Food_Pet_Shop1`
    FOREIGN KEY (`Pet_Shop_idPetShop`)
    REFERENCES `mydb`.`Pet_Shop` (`idPetShop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Food_Donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Food_Donation` (
  `Pet_Shop_idPetShop` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `amount` DECIMAL(3) NOT NULL,
  `time` DATETIME NOT NULL DEFAULT current_timeStamp,
  INDEX `fk_Food_Donation_Pet_Shop1_idx` (`Pet_Shop_idPetShop` ASC),
  INDEX `fk_Food_Donation_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Food_Donation_Pet_Shop1`
    FOREIGN KEY (`Pet_Shop_idPetShop`)
    REFERENCES `mydb`.`Pet_Shop` (`idPetShop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Food_Donation_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
